-- Create user_statistics table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.user_statistics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  questions_answered INTEGER DEFAULT 0,
  correct_answers INTEGER DEFAULT 0,
  UNIQUE(user_id)
);

-- Enable RLS on the table
ALTER TABLE public.user_statistics ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view their own statistics
CREATE POLICY "Users can view own statistics"
ON public.user_statistics
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Allow authenticated users to update their own statistics
CREATE POLICY "Users can update own statistics"
ON public.user_statistics
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Allow authenticated users to insert their own statistics
CREATE POLICY "Users can insert own statistics"
ON public.user_statistics
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Verify that RLS is enabled on the table
SELECT tablename, rowsecurity FROM pg_tables WHERE tablename = 'user_statistics'; 